*Name: Darrell Percey  Lab6  
*Program: Runs an infinite loop of adding M and N after placing
*them into registers A and B. Then stores the value of the 
*added numbers into the variable sum. 

HPRIO	EQU 	$103C
MASK	EQU 	$F5
	ORG 	$0200
M	RMB 	1	; RESERVE 1 BYTE FOR M AT BEGINNING OF EXTERNAL RAM
N	RMB 	1	; RESERVE 1 BYTE FOR N AT NEXT MEMORY LOCATION
SUM	RMB 	1	; RESERVE 1 BYTE FOR SUM AT NEXT MEMORY LOCATION
	ORG 	$B600
	LDAA 	#MASK	; CHANGE HPRIO FOR INTERNAL READ VISIBILITY
	STAA 	HPRIO
	LDAA 	#5	; INITIALIZE M TO 5
	STAA 	M
	LDAA 	#4	; INITIALIZE N TO 4
	STAA 	N	
LOOP	LDAA 	M	; LOAD M INTO ACCA
	LDAB 	N	; LOAB N INTO ACCB
	ABA		; ACCA = ACCA + ACCB
	STAA 	SUM	; STORE SUM
	BRA 	LOOP	; LOOP FOREVER
	SWI
